#!/usr/bin/env ruby
require "digest"; require "json"; require "open3"; require "optparse"; require "pathname"; require "psych"; require "set"; require "yaml"
class C1BRW002NeutralVerifier
 P="config/character/CharacterProportionProfile-C1B-RW-001-r02.yaml"; M="BlenderSource/Characters/C1B-RW-002-r02/GenerationManifest.yaml"; R="BlenderSource/Characters/C1B-RW-002-r02/MeasurementReport.yaml"; S="BlenderSource/Characters/C1B-RW-002-r02/CHR_MasterCharacter_C1B_NeutralRework_r02.blend"; I="tools/blender/inspect_c1b_rw002_neutral.py"; BS=520225; BSH="548a786a50eb28dc8e2b12fe2cf2ddc4032471d8774ff1fa4c02e0f667d6e252"
 def initialize(root,blender:false);@root=Pathname(root).expand_path;@blender=blender;@v=[]end
 def run
  pd=load(P,"PROFILE");md=load(M,"MANIFEST");rd=load(R,"REPORT");@p=h(pd&&pd["CharacterProportionProfile"]);@m=h(md&&md["GenerationManifest"]);@r=h(rd&&rd["C1BRW002MeasurementReport"])
  ck(@p.values_at("profileId","state","candidateStatus","ownerTask","sourceOwner")==["CharacterProportionProfile-C1BRW-001-r02","START","USER_REVIEW","C1BRW-001","kjh4845"],"PROFILE_METADATA")
  ck(h(@p["predecessor"])["status"]=="SUPERSEDED_IMMUTABLE","PROFILE_PREDECESSOR"); mesh=h(@p["neutralMeshContract"]);ck(mesh.values_at("renderMeshObjects","renderMeshDatablocks","connectedClosedComponents","componentVertexCounts","vertices","edges","polygons","boundaryEdges","nonManifoldEdges","looseEdges","degenerateFaces","nonFiniteVertices","materialSlots","uvLayers")==[1,1,2,[10784,610],11394,24864,13470,0,0,0,0,0,1,0],"PROFILE_MESH")
  ck(h(@p["visualIntent"])=={"headShape"=>"ROUND","visibleNeckAllowed"=>false,"headAttachment"=>"DIRECT_OVERLAP_TORSO_ATTACHMENT","torsoArmVisibleSeamAllowed"=>false},"PROFILE_INTENT");ck(h(@p["reviewConstructionBoundary"])["construction"]=="SEAMLESS_BODY_FIELD_PLUS_DIRECT_HEAD_OVERLAP"&&h(@p["reviewConstructionBoundary"])["oldGraphCapPegOrPartGeometryAllowed"]==false,"PROFILE_CONSTRUCTION");gates(h(@p["geometryValidation"]),"PROFILE")
  gate=h(@p["neutralVisualGate"]);ck(gate.values_at("gateId","state","userVisualApprovalRecorded","requiredBeforePoseWork","requiredBeforeFbxExport","poseGenerationAllowed","fbxExportAllowed","unityImportAllowed")==["UG-C1B-NEUTRAL","PENDING_USER_REVIEW",false,true,true,false,false,false],"PROFILE_GATE");ck(h(@p["execution"]).values.all?{|x|x==0},"PROFILE_EXECUTION");walk(@p){|x|bad("ILLEGAL_APPROVAL") if %w[APPROVED LOCKED].include?(x)}
  ck(@m.values_at("state","candidateStatus","ownerTask","sourceOwner")==["START","USER_REVIEW","C1BRW-002","kjh4845"],"MANIFEST_METADATA");b=h(h(@m["stages"])["blend-source"]);ck(b.values_at("status","path","bytes","sha256","lfsState","coreCommit","indexPointerBytes","indexPointerVerified","remoteObjectRoundTripVerified")==["COMPLETE",S,BS,BSH,"VERIFIED_REMOTE_ROUND_TRIP","99302fca3ed482067e52250824b4180ae115b734",131,true,true],"MANIFEST_BLEND");ck(h(@m["predecessor"])["sourceStatus"]=="SUPERSEDED_IMMUTABLE"&&h(@m["predecessor"])["priorArtifactsRewritten"]==false,"MANIFEST_PREDECESSOR")
  stages=h(@m["stages"]);ck(h(stages["pose-generation"])=={"status"=>"BLOCKED_PENDING_NEUTRAL_VISUAL_GATE","outputs"=>0},"MANIFEST_POSE_BLOCK");ck(h(stages["fbx-export"])=={"status"=>"BLOCKED_PENDING_NEUTRAL_VISUAL_GATE","executed"=>false},"MANIFEST_FBX_BLOCK");ck(h(stages["unity-import"])=={"status"=>"BLOCKED_PENDING_NEUTRAL_VISUAL_GATE","executed"=>false},"MANIFEST_UNITY_BLOCK");mg=h(@m["neutralVisualGate"]);ck(mg=={"gateId"=>"UG-C1B-NEUTRAL","state"=>"PENDING_USER_REVIEW","poseGenerationAllowed"=>false,"fbxExportAllowed"=>false,"unityImportAllowed"=>false},"MANIFEST_GATE");ck(h(@m["sourceBoundary"]).values_at("armatures","actions","colliders","uvLayers","weightedVertexAssignments","lodObjects","externalOrPackedInputs","oldGraphCapPegOrPartGeometry")==[0,0,0,0,0,0,0,0],"MANIFEST_BOUNDARY");ck(h(@m["execution"]).values_at("poseOutputs","fbxExports","unityImports","armatures","actions","colliders","playerBuilds")==[0,0,0,0,0,0,0],"MANIFEST_EXECUTION")
  geo=h(@r["geometry"]);ck(geo.values_at("connectedClosedComponents","componentVertexCounts","vertices","edges","polygons","boundaryEdges","nonManifoldEdges","looseEdges","degenerateFaces","uvLayers","positionSha256","orientedTopologySha256")==[2,[10784,610],11394,24864,13470,0,0,0,0,0,"1da184a2ec70246f0e1f26e752523210f0775459572c5f87d3c3af8cce68a98c","6b15f47eb0efee68019f44ce4014c2285387155510211becc23f4142c8233a13"],"REPORT_GEOMETRY");c=h(@r["construction"]);ck(c.values_at("mode","headShape","visibleNeckAllowed","neckSemanticElementCount","headAttachment","torsoArmVisibleSeamAllowed","oldGraphCapPegOrPartGeometryCount")==["SEAMLESS_BODY_FIELD_PLUS_DIRECT_HEAD_OVERLAP","ROUND",false,0,"DIRECT_OVERLAP_TORSO_ATTACHMENT",false,0],"REPORT_CONSTRUCTION");gates(h(@r["geometryGates"]),"REPORT")
  file(S,BS,BSH,"SOURCE");refs;blender if @blender;puts "C1BRW002_R02_AUDIT\nPROFILE_STATE=#{@p['state']}\nSOURCE_HASH_MATCH=#{sha(S)==BSH}\nBLENDER_VERIFIED=#{@bv==true}\nTOTAL_VIOLATIONS=#{@v.size}";@v.each{|x|puts "VIOLATION rule=#{x}"};puts "FINAL_RESULT=#{@v.empty? ? 'PASS':'FAIL'}";@v.empty? ? 0:1
 rescue=>e;bad("VERIFIER_INTERNAL_ERROR_#{e.class}");puts "TOTAL_VIOLATIONS=#{@v.size}";@v.each{|x|puts "VIOLATION rule=#{x}"};puts "FINAL_RESULT=FAIL";1 end
 def gates(g,l)
  if l=="PROFILE";s=h(g["symmetry"]);q=h(g["shoulderContinuity"]);d=h(g["headRoundness"]);a=h(g["directAttachment"]);ck(s["method"]=="SAMPLED_GEOMETRY_ENVELOPE_NOT_TOPOLOGY_MAPPING"&&s["observedDeviationH"]<=s["maximumDeviationH"],"PROFILE_SYMMETRY");ck(q["observedP95Degrees"]<=q["maximumP95Degrees"]&&q["observedSevereEdges"]<=q["maximumSevereEdges"],"PROFILE_SHOULDER");ck(d["observedCoefficientOfVariation"]<=d["maximumCoefficientOfVariation"],"PROFILE_HEAD");ck(a["method"]=="CLOSED_COMPONENT_BVH_SURFACE_INTERSECTION"&&a["neckSemanticElementCount"]==0&&a["observedOverlapH"].all?{|x|x>=a["minimumOverlapH"]}&&a["observedTriangleIntersectionPairs"]>=a["minimumTriangleIntersectionPairs"],"PROFILE_ATTACHMENT")
  else;s=h(g["symmetry"]);q=h(g["shoulderContinuity"]);d=h(g["headRoundness"]);a=h(g["directAttachment"]);ck(s["observedH"]<=s["thresholdH"]&&s["result"]=="PASS","REPORT_SYMMETRY");ck(q["observedP95Degrees"]<=q["p95ThresholdDegrees"]&&q["observedSevereCount"]<=q["severeCountLimit"]&&q["result"]=="PASS","REPORT_SHOULDER");ck(d["observedCoefficient"]<=d["coefficientThreshold"]&&d["result"]=="PASS","REPORT_HEAD");ck(a["method"]=="CLOSED_COMPONENT_BVH_SURFACE_INTERSECTION"&&a["observedOverlapH"].all?{|x|x>=a["minimumOverlapH"]}&&a["observedTriangleIntersectionPairs"]>=a["minimumTriangleIntersectionPairs"]&&a["result"]=="PASS","REPORT_ATTACHMENT")end end
 def refs
  pr=h(h(@m["stages"])["profile"]);mr=h(@m["measurementEvidence"]);ck(pr["path"]==P&&pr["sha256"]==sha(P),"MANIFEST_PROFILE_REF");ck(mr["path"]==R&&mr["sha256"]==sha(R),"MANIFEST_REPORT_REF");ren=h(h(@m["stages"])["reference-render"]);o=Array(ren["outputs"]);ck(o.size==8&&ren["dimensions"]==[2048,2048],"RENDER_SET");bundle=Digest::SHA256.hexdigest(o.sort_by{|e|e["path"]}.map{|e|"#{e['path']}=#{e['sha256']}\n"}.join);ck(ren["orderedBundleSha256"]==bundle&&bundle=="d0456c9495070cd5659fdd9f6004b489c8ccfb5ca9bae3b2208fe83301cf37e1","RENDER_BUNDLE_SHA");o.each{|e|file(e["path"],e["bytes"],e["sha256"],"RENDER");ck(png(e["path"])==[2048,2048],"RENDER_DIMENSIONS")};h(@m["generationTools"]).each{|n,e|ck(e["sha256"]==sha(e["path"]),"TOOL_#{n.upcase}_SHA")}
  expected=([S,M,R]+o.map{|e|e["path"]}).sort;actual=Dir[@root.join("BlenderSource/Characters/C1B-RW-002-r02/**/*")].select{|x|File.file?(x)}.map{|x|Pathname(x).relative_path_from(@root).to_s}.sort;ck(actual==expected,"RW002_R02_FILE_SET")
 end
 def blender
  out,_,st=Open3.capture3("/Applications/Blender.app/Contents/MacOS/Blender","-b",@root.join(S).to_s,"--python",@root.join(I).to_s);ck(st.success?,"BLENDER_EXEC");j=JSON.parse(out[/C1BRW002_INSPECTION_JSON=(\{.*\})/,1]||"{}");ck(j["errors"]==[],"BLENDER_ERRORS");m=h(j["mesh"]);ck(m.values_at("vertices","edges","polygons","connectedComponents","componentVertexCounts","uvLayers")==[11394,24864,13470,2,[10784,610],0],"BLENDER_MESH");g=h(j["geometryGates"]);contract=h(g["constructionContract"]);ck(contract.values_at("construction","headShape","visibleNeckAllowed","headAttachment","torsoArmVisibleSeamAllowed")==["SEAMLESS_BODY_FIELD_PLUS_DIRECT_HEAD_OVERLAP","ROUND",false,"DIRECT_OVERLAP_TORSO_ATTACHMENT",false],"BLENDER_CONSTRUCTION");ck(g["neckSemanticElementCount"]==0&&g["sampledEnvelopeMaximumMirrorDeviationH"]<=0.003&&g["shoulderDihedralP95Degrees"]<=20&&g["shoulderSevereEdgeCount"]<=4&&g["headRadialCoefficientOfVariation"]<=0.12&&g["headBodyOverlapH"].all?{|x|x>=0.005}&&g["headBodyTriangleIntersectionPairs"]>=1,"BLENDER_GEOMETRY_GATES");@bv=@v.empty?
 end
 def load(rel,l)
  p=@root.join(rel);return bad("#{l}_MISSING") unless p.file?&&!p.symlink?;return bad("#{l}_TOO_LARGE") if p.size>524288;t=p.read
  begin
   f=->(n){if n.is_a?(Psych::Nodes::Mapping);local=Set.new;n.children.each_slice(2){|k,v|bad("#{l}_YAML_DUPLICATE_KEY") unless local.add?(k.value);f.call(v)}elsif n.respond_to?(:children)&&n.children;n.children.each{|c|f.call(c)}end};f.call(Psych.parse_stream(t));YAML.safe_load(t,aliases:false)
  rescue Psych::Exception
   bad("#{l}_YAML_INVALID")
  end
 end
 def file(r,b,s,l);p=@root.join(r);ck(p.file?&&!p.symlink?,"#{l}_MISSING");return unless p.file?;ck(p.size==b,"#{l}_SIZE");ck(sha(r)==s,"#{l}_SHA")end;def png(r);d=@root.join(r).binread(24);d[16,8].unpack("NN") rescue nil end;def sha(r);p=@root.join(r);p.file? ? Digest::SHA256.file(p).hexdigest : nil end;def h(x);x.is_a?(Hash) ? x : {} end;def ck(x,r);bad(r) unless x end;def bad(r);@v<<r unless @v.include?(r);nil end;def walk(x,&b);yield x;x.each_value{|v|walk(v,&b)}if x.is_a?(Hash);x.each{|v|walk(v,&b)}if x.is_a?(Array)end
end
o={};OptionParser.new{|x|x.on("--root PATH"){|v|o[:root]=v};x.on("--verify-blender"){o[:blender]=true}}.parse!;exit C1BRW002NeutralVerifier.new(o.fetch(:root,Pathname(__dir__).join("..")),blender:o[:blender]).run
